// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3pIykjo1bGgaYcgboov_8YbelpcXDrGI',
    appId: '1:440510340616:web:df860b58a7a0f415567bbd',
    messagingSenderId: '440510340616',
    projectId: 'mipuntodeventapc',
    authDomain: 'mipuntodeventapc.firebaseapp.com',
    storageBucket: 'mipuntodeventapc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw1SgchUFajkxm1gx__ro50uUl20aNAR8',
    appId: '1:440510340616:android:61978fe948afed1a567bbd',
    messagingSenderId: '440510340616',
    projectId: 'mipuntodeventapc',
    storageBucket: 'mipuntodeventapc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd9sxuYY10ygAM0g-tGsArSotBuGnQBW0',
    appId: '1:440510340616:ios:e82799264ece45cc567bbd',
    messagingSenderId: '440510340616',
    projectId: 'mipuntodeventapc',
    storageBucket: 'mipuntodeventapc.firebasestorage.app',
    iosBundleId: 'com.example.miPuntoDeVenta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd9sxuYY10ygAM0g-tGsArSotBuGnQBW0',
    appId: '1:440510340616:ios:e82799264ece45cc567bbd',
    messagingSenderId: '440510340616',
    projectId: 'mipuntodeventapc',
    storageBucket: 'mipuntodeventapc.firebasestorage.app',
    iosBundleId: 'com.example.miPuntoDeVenta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3pIykjo1bGgaYcgboov_8YbelpcXDrGI',
    appId: '1:440510340616:web:c4f2ad510001dc8e567bbd',
    messagingSenderId: '440510340616',
    projectId: 'mipuntodeventapc',
    authDomain: 'mipuntodeventapc.firebaseapp.com',
    storageBucket: 'mipuntodeventapc.firebasestorage.app',
  );

}